version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./api
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    # Файл содержащий переменные для контейнера
#    env_file:
#      - ./.env.dev
  front:
    # Берем Dockerfile из каталога app
    build: ./blog_nuxt_v1
    # Запускаем тестовый сервер
    command: npm start
    ports:
      - "5000:5000"
