version: '3.8'

# https://www.youtube.com/watch?v=oOR-hPHnTC0

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./api
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    expose:
      - 8000
    # Файл содержащий переменные для контейнера
#    env_file:
#      - ./.env.dev
  front:
    # Берем Dockerfile из каталога app
    build: ./blog_nuxt_v1
    # Запускаем тестовый сервер
    command: npm start
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      env_file:
      - ./.env.nuxt